server:
  port: 8081

spring:
  application:
    name: CUSTOMER-SERVICE

  datasource:
    url: jdbc:postgresql://localhost:5432/insurance_db
    username: postgres
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  instance:
    prefer-ip-address: true        # ✅ FIX (important)
    ip-address: 127.0.0.1         # ✅ FIX (important)

  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
